// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Orders               []*Order `protobuf:"bytes,4,rep,name=orders,proto3" json:"orders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

type CreateUserReq struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateUserRes struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRes) Reset()         { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()    {}
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRes.Unmarshal(m, b)
}
func (m *CreateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRes.Marshal(b, m, deterministic)
}
func (m *CreateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRes.Merge(m, src)
}
func (m *CreateUserRes) XXX_Size() int {
	return xxx_messageInfo_CreateUserRes.Size(m)
}
func (m *CreateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRes proto.InternalMessageInfo

func (m *CreateUserRes) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

type ReadUserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserReq) Reset()         { *m = ReadUserReq{} }
func (m *ReadUserReq) String() string { return proto.CompactTextString(m) }
func (*ReadUserReq) ProtoMessage()    {}
func (*ReadUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *ReadUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserReq.Unmarshal(m, b)
}
func (m *ReadUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserReq.Marshal(b, m, deterministic)
}
func (m *ReadUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserReq.Merge(m, src)
}
func (m *ReadUserReq) XXX_Size() int {
	return xxx_messageInfo_ReadUserReq.Size(m)
}
func (m *ReadUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserReq proto.InternalMessageInfo

func (m *ReadUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadUserRes struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRes) Reset()         { *m = ReadUserRes{} }
func (m *ReadUserRes) String() string { return proto.CompactTextString(m) }
func (*ReadUserRes) ProtoMessage()    {}
func (*ReadUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *ReadUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRes.Unmarshal(m, b)
}
func (m *ReadUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRes.Marshal(b, m, deterministic)
}
func (m *ReadUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRes.Merge(m, src)
}
func (m *ReadUserRes) XXX_Size() int {
	return xxx_messageInfo_ReadUserRes.Size(m)
}
func (m *ReadUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRes proto.InternalMessageInfo

func (m *ReadUserRes) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateUserReq struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateUserRes struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRes) Reset()         { *m = UpdateUserRes{} }
func (m *UpdateUserRes) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRes) ProtoMessage()    {}
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UpdateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRes.Unmarshal(m, b)
}
func (m *UpdateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRes.Marshal(b, m, deterministic)
}
func (m *UpdateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRes.Merge(m, src)
}
func (m *UpdateUserRes) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRes.Size(m)
}
func (m *UpdateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRes proto.InternalMessageInfo

func (m *UpdateUserRes) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteUserReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRes) Reset()         { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()    {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *DeleteUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRes.Unmarshal(m, b)
}
func (m *DeleteUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRes.Marshal(b, m, deterministic)
}
func (m *DeleteUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRes.Merge(m, src)
}
func (m *DeleteUserRes) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRes.Size(m)
}
func (m *DeleteUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRes proto.InternalMessageInfo

func (m *DeleteUserRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListUserReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserReq) Reset()         { *m = ListUserReq{} }
func (m *ListUserReq) String() string { return proto.CompactTextString(m) }
func (*ListUserReq) ProtoMessage()    {}
func (*ListUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *ListUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserReq.Unmarshal(m, b)
}
func (m *ListUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserReq.Marshal(b, m, deterministic)
}
func (m *ListUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserReq.Merge(m, src)
}
func (m *ListUserReq) XXX_Size() int {
	return xxx_messageInfo_ListUserReq.Size(m)
}
func (m *ListUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserReq proto.InternalMessageInfo

type ListUserRes struct {
	Item                 *User    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRes) Reset()         { *m = ListUserRes{} }
func (m *ListUserRes) String() string { return proto.CompactTextString(m) }
func (*ListUserRes) ProtoMessage()    {}
func (*ListUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ListUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRes.Unmarshal(m, b)
}
func (m *ListUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRes.Marshal(b, m, deterministic)
}
func (m *ListUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRes.Merge(m, src)
}
func (m *ListUserRes) XXX_Size() int {
	return xxx_messageInfo_ListUserRes.Size(m)
}
func (m *ListUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRes proto.InternalMessageInfo

func (m *ListUserRes) GetItem() *User {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*CreateUserReq)(nil), "proto.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "proto.CreateUserRes")
	proto.RegisterType((*ReadUserReq)(nil), "proto.ReadUserReq")
	proto.RegisterType((*ReadUserRes)(nil), "proto.ReadUserRes")
	proto.RegisterType((*UpdateUserReq)(nil), "proto.UpdateUserReq")
	proto.RegisterType((*UpdateUserRes)(nil), "proto.UpdateUserRes")
	proto.RegisterType((*DeleteUserReq)(nil), "proto.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "proto.DeleteUserRes")
	proto.RegisterType((*ListUserReq)(nil), "proto.ListUserReq")
	proto.RegisterType((*ListUserRes)(nil), "proto.ListUserRes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xe9, 0x87, 0xed, 0xac, 0xf5, 0x30, 0xf4, 0x10, 0x16, 0xa4, 0x25, 0x78, 0xa8, 0x97,
	0x50, 0x22, 0x82, 0x77, 0x3d, 0x0a, 0x42, 0xa4, 0x3f, 0x20, 0x66, 0xe7, 0xb0, 0xd0, 0x9a, 0xb8,
	0x93, 0xea, 0x3f, 0xf2, 0x77, 0x4a, 0xb6, 0xf9, 0x6e, 0xa0, 0xf5, 0xb4, 0xcc, 0x7b, 0xf3, 0xf6,
	0xbd, 0x7d, 0x0b, 0x70, 0x60, 0x32, 0x7e, 0x6a, 0x92, 0x2c, 0xc1, 0xb1, 0x3d, 0xa4, 0x48, 0x8c,
	0x2a, 0x31, 0xef, 0x13, 0x46, 0x5b, 0x26, 0x83, 0x37, 0xe0, 0x68, 0xe5, 0x0e, 0x56, 0x83, 0xf5,
	0x2c, 0x74, 0xb4, 0xc2, 0x05, 0x8c, 0x69, 0x1f, 0xe9, 0x9d, 0xeb, 0x58, 0xe8, 0x38, 0xa0, 0x84,
	0x69, 0x1a, 0x31, 0xff, 0x24, 0x46, 0xb9, 0x43, 0x4b, 0x54, 0x33, 0xde, 0xc1, 0xc4, 0x5e, 0xcc,
	0xee, 0x68, 0x35, 0x5c, 0x8b, 0xe0, 0xfa, 0xe8, 0xe0, 0xbf, 0xe5, 0x60, 0x58, 0x70, 0xde, 0x06,
	0xe6, 0xcf, 0x86, 0xa2, 0x8c, 0x72, 0xd7, 0x90, 0xbe, 0x70, 0x09, 0x23, 0x9d, 0xd1, 0xde, 0x5a,
	0x8b, 0x40, 0x14, 0x22, 0xcb, 0x5a, 0xa2, 0xab, 0xe0, 0xf3, 0x8a, 0x5b, 0x10, 0x21, 0x45, 0xaa,
	0x74, 0xe8, 0x3c, 0xcd, 0xf3, 0x9b, 0x34, 0x5f, 0x14, 0x60, 0x9b, 0xaa, 0x7f, 0x46, 0x6e, 0x2a,
	0x2e, 0xf0, 0x58, 0xc2, 0xfc, 0x85, 0x76, 0x54, 0x7b, 0x74, 0x43, 0xdf, 0xb7, 0x17, 0x18, 0x5d,
	0xb8, 0xe2, 0x43, 0x1c, 0x13, 0xb3, 0xdd, 0x9a, 0x86, 0xe5, 0xe8, 0xcd, 0x41, 0xbc, 0x6a, 0xce,
	0x8a, 0x9b, 0xf2, 0xe7, 0xd6, 0xe3, 0xf9, 0x28, 0xc1, 0xaf, 0x03, 0x22, 0x1f, 0xdf, 0xc9, 0x7c,
	0xeb, 0x98, 0xf0, 0x09, 0xa0, 0xee, 0x1f, 0x17, 0x85, 0xa0, 0xf5, 0x89, 0xb2, 0x0f, 0x65, 0x0c,
	0x60, 0x5a, 0x16, 0x8d, 0x58, 0x6c, 0x34, 0x3e, 0x46, 0x9e, 0x62, 0x9c, 0xbb, 0xd5, 0xd5, 0x55,
	0x6e, 0xad, 0xfe, 0x65, 0x1f, 0x6a, 0x95, 0x75, 0x43, 0x95, 0xb2, 0xd5, 0xaa, 0xec, 0x43, 0x19,
	0x1f, 0x61, 0x56, 0x36, 0xc4, 0x55, 0xd0, 0x46, 0x85, 0xf2, 0x14, 0xe3, 0xcd, 0xe0, 0x63, 0x62,
	0xc1, 0x87, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x31, 0x1d, 0x3d, 0xd8, 0x63, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error)
	ReadUser(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error)
	ListUsers(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (UserService_ListUsersClient, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error) {
	out := new(CreateUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadUser(ctx context.Context, in *ReadUserReq, opts ...grpc.CallOption) (*ReadUserRes, error) {
	out := new(ReadUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	out := new(UpdateUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error) {
	out := new(DeleteUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUserReq, opts ...grpc.CallOption) (UserService_ListUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_UserService_serviceDesc.Streams[0], "/proto.UserService/ListUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceListUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_ListUsersClient interface {
	Recv() (*ListUserRes, error)
	grpc.ClientStream
}

type userServiceListUsersClient struct {
	grpc.ClientStream
}

func (x *userServiceListUsersClient) Recv() (*ListUserRes, error) {
	m := new(ListUserRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *CreateUserReq) (*CreateUserRes, error)
	ReadUser(context.Context, *ReadUserReq) (*ReadUserRes, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserRes, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
	ListUsers(*ListUserReq, UserService_ListUsersServer) error
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) ReadUser(ctx context.Context, req *ReadUserReq) (*ReadUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedUserServiceServer) ListUsers(req *ListUserReq, srv UserService_ListUsersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadUser(ctx, req.(*ReadUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListUserReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).ListUsers(m, &userServiceListUsersServer{stream})
}

type UserService_ListUsersServer interface {
	Send(*ListUserRes) error
	grpc.ServerStream
}

type userServiceListUsersServer struct {
	grpc.ServerStream
}

func (x *userServiceListUsersServer) Send(m *ListUserRes) error {
	return x.ServerStream.SendMsg(m)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _UserService_ReadUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListUsers",
			Handler:       _UserService_ListUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}
