// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemName             string   `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	ItemDescription      string   `protobuf:"bytes,3,opt,name=item_description,json=itemDescription,proto3" json:"item_description,omitempty"`
	ItemImg              string   `protobuf:"bytes,4,opt,name=item_img,json=itemImg,proto3" json:"item_img,omitempty"`
	ItemPrice            float32  `protobuf:"fixed32,5,opt,name=item_price,json=itemPrice,proto3" json:"item_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *Item) GetItemDescription() string {
	if m != nil {
		return m.ItemDescription
	}
	return ""
}

func (m *Item) GetItemImg() string {
	if m != nil {
		return m.ItemImg
	}
	return ""
}

func (m *Item) GetItemPrice() float32 {
	if m != nil {
		return m.ItemPrice
	}
	return 0
}

type CreateItemReq struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemReq) Reset()         { *m = CreateItemReq{} }
func (m *CreateItemReq) String() string { return proto.CompactTextString(m) }
func (*CreateItemReq) ProtoMessage()    {}
func (*CreateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{1}
}

func (m *CreateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemReq.Unmarshal(m, b)
}
func (m *CreateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemReq.Marshal(b, m, deterministic)
}
func (m *CreateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemReq.Merge(m, src)
}
func (m *CreateItemReq) XXX_Size() int {
	return xxx_messageInfo_CreateItemReq.Size(m)
}
func (m *CreateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemReq proto.InternalMessageInfo

func (m *CreateItemReq) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateItemRes struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemRes) Reset()         { *m = CreateItemRes{} }
func (m *CreateItemRes) String() string { return proto.CompactTextString(m) }
func (*CreateItemRes) ProtoMessage()    {}
func (*CreateItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{2}
}

func (m *CreateItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemRes.Unmarshal(m, b)
}
func (m *CreateItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemRes.Marshal(b, m, deterministic)
}
func (m *CreateItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemRes.Merge(m, src)
}
func (m *CreateItemRes) XXX_Size() int {
	return xxx_messageInfo_CreateItemRes.Size(m)
}
func (m *CreateItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemRes proto.InternalMessageInfo

func (m *CreateItemRes) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type ReadItemReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadItemReq) Reset()         { *m = ReadItemReq{} }
func (m *ReadItemReq) String() string { return proto.CompactTextString(m) }
func (*ReadItemReq) ProtoMessage()    {}
func (*ReadItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{3}
}

func (m *ReadItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadItemReq.Unmarshal(m, b)
}
func (m *ReadItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadItemReq.Marshal(b, m, deterministic)
}
func (m *ReadItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadItemReq.Merge(m, src)
}
func (m *ReadItemReq) XXX_Size() int {
	return xxx_messageInfo_ReadItemReq.Size(m)
}
func (m *ReadItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadItemReq proto.InternalMessageInfo

func (m *ReadItemReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadItemRes struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadItemRes) Reset()         { *m = ReadItemRes{} }
func (m *ReadItemRes) String() string { return proto.CompactTextString(m) }
func (*ReadItemRes) ProtoMessage()    {}
func (*ReadItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{4}
}

func (m *ReadItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadItemRes.Unmarshal(m, b)
}
func (m *ReadItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadItemRes.Marshal(b, m, deterministic)
}
func (m *ReadItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadItemRes.Merge(m, src)
}
func (m *ReadItemRes) XXX_Size() int {
	return xxx_messageInfo_ReadItemRes.Size(m)
}
func (m *ReadItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadItemRes proto.InternalMessageInfo

func (m *ReadItemRes) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemReq struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemReq) Reset()         { *m = UpdateItemReq{} }
func (m *UpdateItemReq) String() string { return proto.CompactTextString(m) }
func (*UpdateItemReq) ProtoMessage()    {}
func (*UpdateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{5}
}

func (m *UpdateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemReq.Unmarshal(m, b)
}
func (m *UpdateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemReq.Marshal(b, m, deterministic)
}
func (m *UpdateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemReq.Merge(m, src)
}
func (m *UpdateItemReq) XXX_Size() int {
	return xxx_messageInfo_UpdateItemReq.Size(m)
}
func (m *UpdateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemReq proto.InternalMessageInfo

func (m *UpdateItemReq) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemRes struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemRes) Reset()         { *m = UpdateItemRes{} }
func (m *UpdateItemRes) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRes) ProtoMessage()    {}
func (*UpdateItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{6}
}

func (m *UpdateItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRes.Unmarshal(m, b)
}
func (m *UpdateItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRes.Marshal(b, m, deterministic)
}
func (m *UpdateItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRes.Merge(m, src)
}
func (m *UpdateItemRes) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRes.Size(m)
}
func (m *UpdateItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRes proto.InternalMessageInfo

func (m *UpdateItemRes) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteItemReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemReq) Reset()         { *m = DeleteItemReq{} }
func (m *DeleteItemReq) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReq) ProtoMessage()    {}
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{7}
}

func (m *DeleteItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReq.Unmarshal(m, b)
}
func (m *DeleteItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReq.Marshal(b, m, deterministic)
}
func (m *DeleteItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReq.Merge(m, src)
}
func (m *DeleteItemReq) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReq.Size(m)
}
func (m *DeleteItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReq proto.InternalMessageInfo

func (m *DeleteItemReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteItemRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRes) Reset()         { *m = DeleteItemRes{} }
func (m *DeleteItemRes) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRes) ProtoMessage()    {}
func (*DeleteItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{8}
}

func (m *DeleteItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRes.Unmarshal(m, b)
}
func (m *DeleteItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRes.Marshal(b, m, deterministic)
}
func (m *DeleteItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRes.Merge(m, src)
}
func (m *DeleteItemRes) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRes.Size(m)
}
func (m *DeleteItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRes proto.InternalMessageInfo

func (m *DeleteItemRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListItemReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemReq) Reset()         { *m = ListItemReq{} }
func (m *ListItemReq) String() string { return proto.CompactTextString(m) }
func (*ListItemReq) ProtoMessage()    {}
func (*ListItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{9}
}

func (m *ListItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemReq.Unmarshal(m, b)
}
func (m *ListItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemReq.Marshal(b, m, deterministic)
}
func (m *ListItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemReq.Merge(m, src)
}
func (m *ListItemReq) XXX_Size() int {
	return xxx_messageInfo_ListItemReq.Size(m)
}
func (m *ListItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemReq proto.InternalMessageInfo

type ListItemRes struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListItemRes) Reset()         { *m = ListItemRes{} }
func (m *ListItemRes) String() string { return proto.CompactTextString(m) }
func (*ListItemRes) ProtoMessage()    {}
func (*ListItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{10}
}

func (m *ListItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemRes.Unmarshal(m, b)
}
func (m *ListItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemRes.Marshal(b, m, deterministic)
}
func (m *ListItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemRes.Merge(m, src)
}
func (m *ListItemRes) XXX_Size() int {
	return xxx_messageInfo_ListItemRes.Size(m)
}
func (m *ListItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemRes proto.InternalMessageInfo

func (m *ListItemRes) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*CreateItemReq)(nil), "proto.CreateItemReq")
	proto.RegisterType((*CreateItemRes)(nil), "proto.CreateItemRes")
	proto.RegisterType((*ReadItemReq)(nil), "proto.ReadItemReq")
	proto.RegisterType((*ReadItemRes)(nil), "proto.ReadItemRes")
	proto.RegisterType((*UpdateItemReq)(nil), "proto.UpdateItemReq")
	proto.RegisterType((*UpdateItemRes)(nil), "proto.UpdateItemRes")
	proto.RegisterType((*DeleteItemReq)(nil), "proto.DeleteItemReq")
	proto.RegisterType((*DeleteItemRes)(nil), "proto.DeleteItemRes")
	proto.RegisterType((*ListItemReq)(nil), "proto.ListItemReq")
	proto.RegisterType((*ListItemRes)(nil), "proto.ListItemRes")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0xc1, 0x6a, 0xc2, 0x50,
	0x10, 0x24, 0xa9, 0x56, 0xdd, 0x60, 0x5b, 0x96, 0x1e, 0xd2, 0x14, 0x51, 0x72, 0xd2, 0x8b, 0x88,
	0xa5, 0xd0, 0x7b, 0xbd, 0x08, 0xa5, 0x94, 0x94, 0x9e, 0x25, 0x4d, 0x16, 0x79, 0xd0, 0x68, 0x9a,
	0x4d, 0xfb, 0x2d, 0xfd, 0x82, 0x7e, 0x67, 0x79, 0xab, 0xf1, 0x25, 0x1a, 0xd0, 0x9e, 0xc2, 0xce,
	0xce, 0x64, 0xe6, 0xcd, 0x02, 0xa8, 0x9c, 0x92, 0x71, 0x9a, 0xad, 0xf3, 0x35, 0x36, 0xe5, 0xe3,
	0xff, 0x58, 0xd0, 0x98, 0xe7, 0x94, 0xe0, 0x05, 0xd8, 0x2a, 0x76, 0xad, 0x81, 0x35, 0xec, 0x04,
	0xb6, 0x8a, 0xf1, 0x16, 0x3a, 0x9a, 0xbd, 0x58, 0x85, 0x09, 0xb9, 0xb6, 0xc0, 0x6d, 0x0d, 0x3c,
	0x87, 0x09, 0xe1, 0x08, 0xae, 0x64, 0x19, 0x13, 0x47, 0x99, 0x4a, 0x73, 0xb5, 0x5e, 0xb9, 0x67,
	0xc2, 0xb9, 0xd4, 0xf8, 0xcc, 0xc0, 0x78, 0x03, 0x22, 0x5b, 0xa8, 0x64, 0xe9, 0x36, 0x84, 0xd2,
	0xd2, 0xf3, 0x3c, 0x59, 0x62, 0x6f, 0x13, 0x68, 0x91, 0x66, 0x2a, 0x22, 0xb7, 0x39, 0xb0, 0x86,
	0x76, 0x20, 0xa6, 0x2f, 0x1a, 0xf0, 0x27, 0xd0, 0x7d, 0xcc, 0x28, 0xcc, 0x49, 0xe7, 0x0b, 0xe8,
	0x13, 0xfb, 0xd0, 0xd0, 0x5b, 0x09, 0xe9, 0x4c, 0x9d, 0xcd, 0x43, 0xc6, 0xb2, 0x95, 0xc5, 0xbe,
	0x82, 0x8f, 0x2b, 0x7a, 0xe0, 0x04, 0x14, 0xc6, 0x85, 0xc3, 0x5e, 0x09, 0xfe, 0xb8, 0xbc, 0xe6,
	0x93, 0x02, 0xbc, 0xa5, 0xf1, 0x3f, 0x23, 0x97, 0x15, 0x27, 0x78, 0xf4, 0xa1, 0x3b, 0xa3, 0x0f,
	0x32, 0x1e, 0xfb, 0xa1, 0x47, 0x55, 0x02, 0xa3, 0x0b, 0x2d, 0xfe, 0x8a, 0x22, 0x62, 0x16, 0x56,
	0x3b, 0x28, 0x46, 0xbf, 0x0b, 0xce, 0x93, 0xe2, 0x7c, 0xfb, 0x27, 0xfd, 0x5c, 0x33, 0x1e, 0x8f,
	0x32, 0xfd, 0xb5, 0xc1, 0xd1, 0xe3, 0x2b, 0x65, 0xdf, 0x2a, 0x22, 0x7c, 0x00, 0x30, 0xfd, 0xe3,
	0xf5, 0x56, 0x50, 0x39, 0xa2, 0x57, 0x87, 0x32, 0x4e, 0xa1, 0x5d, 0x14, 0x8d, 0xb8, 0x65, 0x94,
	0x0e, 0xe3, 0x1d, 0x62, 0xac, 0xdd, 0x4c, 0x75, 0x3b, 0xb7, 0x4a, 0xff, 0x5e, 0x1d, 0x2a, 0x4a,
	0xd3, 0xd0, 0x4e, 0x59, 0x69, 0xd5, 0xab, 0x43, 0x19, 0xef, 0xa1, 0x53, 0x34, 0xc4, 0xbb, 0xa0,
	0xa5, 0x0a, 0xbd, 0x43, 0x8c, 0x27, 0xd6, 0xfb, 0xb9, 0x80, 0x77, 0x7f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xaf, 0x7c, 0x3c, 0x49, 0x81, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemServiceClient is the client API for ItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemServiceClient interface {
	CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*CreateItemRes, error)
	ReadItem(ctx context.Context, in *ReadItemReq, opts ...grpc.CallOption) (*ReadItemRes, error)
	UpdateItem(ctx context.Context, in *UpdateItemReq, opts ...grpc.CallOption) (*UpdateItemRes, error)
	DeleteItem(ctx context.Context, in *DeleteItemReq, opts ...grpc.CallOption) (*DeleteItemRes, error)
	ListItems(ctx context.Context, in *ListItemReq, opts ...grpc.CallOption) (ItemService_ListItemsClient, error)
}

type itemServiceClient struct {
	cc *grpc.ClientConn
}

func NewItemServiceClient(cc *grpc.ClientConn) ItemServiceClient {
	return &itemServiceClient{cc}
}

func (c *itemServiceClient) CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*CreateItemRes, error) {
	out := new(CreateItemRes)
	err := c.cc.Invoke(ctx, "/proto.ItemService/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ReadItem(ctx context.Context, in *ReadItemReq, opts ...grpc.CallOption) (*ReadItemRes, error) {
	out := new(ReadItemRes)
	err := c.cc.Invoke(ctx, "/proto.ItemService/ReadItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) UpdateItem(ctx context.Context, in *UpdateItemReq, opts ...grpc.CallOption) (*UpdateItemRes, error) {
	out := new(UpdateItemRes)
	err := c.cc.Invoke(ctx, "/proto.ItemService/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) DeleteItem(ctx context.Context, in *DeleteItemReq, opts ...grpc.CallOption) (*DeleteItemRes, error) {
	out := new(DeleteItemRes)
	err := c.cc.Invoke(ctx, "/proto.ItemService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemServiceClient) ListItems(ctx context.Context, in *ListItemReq, opts ...grpc.CallOption) (ItemService_ListItemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ItemService_serviceDesc.Streams[0], "/proto.ItemService/ListItems", opts...)
	if err != nil {
		return nil, err
	}
	x := &itemServiceListItemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ItemService_ListItemsClient interface {
	Recv() (*ListItemRes, error)
	grpc.ClientStream
}

type itemServiceListItemsClient struct {
	grpc.ClientStream
}

func (x *itemServiceListItemsClient) Recv() (*ListItemRes, error) {
	m := new(ListItemRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ItemServiceServer is the server API for ItemService service.
type ItemServiceServer interface {
	CreateItem(context.Context, *CreateItemReq) (*CreateItemRes, error)
	ReadItem(context.Context, *ReadItemReq) (*ReadItemRes, error)
	UpdateItem(context.Context, *UpdateItemReq) (*UpdateItemRes, error)
	DeleteItem(context.Context, *DeleteItemReq) (*DeleteItemRes, error)
	ListItems(*ListItemReq, ItemService_ListItemsServer) error
}

// UnimplementedItemServiceServer can be embedded to have forward compatible implementations.
type UnimplementedItemServiceServer struct {
}

func (*UnimplementedItemServiceServer) CreateItem(ctx context.Context, req *CreateItemReq) (*CreateItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (*UnimplementedItemServiceServer) ReadItem(ctx context.Context, req *ReadItemReq) (*ReadItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadItem not implemented")
}
func (*UnimplementedItemServiceServer) UpdateItem(ctx context.Context, req *UpdateItemReq) (*UpdateItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (*UnimplementedItemServiceServer) DeleteItem(ctx context.Context, req *DeleteItemReq) (*DeleteItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedItemServiceServer) ListItems(req *ListItemReq, srv ItemService_ListItemsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListItems not implemented")
}

func RegisterItemServiceServer(s *grpc.Server, srv ItemServiceServer) {
	s.RegisterService(&_ItemService_serviceDesc, srv)
}

func _ItemService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemService/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).CreateItem(ctx, req.(*CreateItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ReadItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).ReadItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemService/ReadItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).ReadItem(ctx, req.(*ReadItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemService/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).UpdateItem(ctx, req.(*UpdateItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ItemService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemServiceServer).DeleteItem(ctx, req.(*DeleteItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemService_ListItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListItemReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ItemServiceServer).ListItems(m, &itemServiceListItemsServer{stream})
}

type ItemService_ListItemsServer interface {
	Send(*ListItemRes) error
	grpc.ServerStream
}

type itemServiceListItemsServer struct {
	grpc.ServerStream
}

func (x *itemServiceListItemsServer) Send(m *ListItemRes) error {
	return x.ServerStream.SendMsg(m)
}

var _ItemService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ItemService",
	HandlerType: (*ItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _ItemService_CreateItem_Handler,
		},
		{
			MethodName: "ReadItem",
			Handler:    _ItemService_ReadItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _ItemService_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _ItemService_DeleteItem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListItems",
			Handler:       _ItemService_ListItems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "item.proto",
}
