// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TableNo              int32    `protobuf:"varint,2,opt,name=table_no,json=tableNo,proto3" json:"table_no,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Items                []*Item  `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,5,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	IsPayed              bool     `protobuf:"varint,6,opt,name=is_payed,json=isPayed,proto3" json:"is_payed,omitempty"`
	IsReady              bool     `protobuf:"varint,7,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetTableNo() int32 {
	if m != nil {
		return m.TableNo
	}
	return 0
}

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *Order) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *Order) GetIsPayed() bool {
	if m != nil {
		return m.IsPayed
	}
	return false
}

func (m *Order) GetIsReady() bool {
	if m != nil {
		return m.IsReady
	}
	return false
}

type CreateOrderReq struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateOrderRes struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRes) Reset()         { *m = CreateOrderRes{} }
func (m *CreateOrderRes) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRes) ProtoMessage()    {}
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *CreateOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRes.Unmarshal(m, b)
}
func (m *CreateOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRes.Marshal(b, m, deterministic)
}
func (m *CreateOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRes.Merge(m, src)
}
func (m *CreateOrderRes) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRes.Size(m)
}
func (m *CreateOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRes proto.InternalMessageInfo

func (m *CreateOrderRes) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

type ReadOrderReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderReq) Reset()         { *m = ReadOrderReq{} }
func (m *ReadOrderReq) String() string { return proto.CompactTextString(m) }
func (*ReadOrderReq) ProtoMessage()    {}
func (*ReadOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *ReadOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderReq.Unmarshal(m, b)
}
func (m *ReadOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderReq.Marshal(b, m, deterministic)
}
func (m *ReadOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderReq.Merge(m, src)
}
func (m *ReadOrderReq) XXX_Size() int {
	return xxx_messageInfo_ReadOrderReq.Size(m)
}
func (m *ReadOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderReq proto.InternalMessageInfo

func (m *ReadOrderReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadOrderRes struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOrderRes) Reset()         { *m = ReadOrderRes{} }
func (m *ReadOrderRes) String() string { return proto.CompactTextString(m) }
func (*ReadOrderRes) ProtoMessage()    {}
func (*ReadOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *ReadOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOrderRes.Unmarshal(m, b)
}
func (m *ReadOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOrderRes.Marshal(b, m, deterministic)
}
func (m *ReadOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOrderRes.Merge(m, src)
}
func (m *ReadOrderRes) XXX_Size() int {
	return xxx_messageInfo_ReadOrderRes.Size(m)
}
func (m *ReadOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOrderRes proto.InternalMessageInfo

func (m *ReadOrderRes) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateOrderReq struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderReq) Reset()         { *m = UpdateOrderReq{} }
func (m *UpdateOrderReq) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderReq) ProtoMessage()    {}
func (*UpdateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *UpdateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderReq.Unmarshal(m, b)
}
func (m *UpdateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderReq.Marshal(b, m, deterministic)
}
func (m *UpdateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderReq.Merge(m, src)
}
func (m *UpdateOrderReq) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderReq.Size(m)
}
func (m *UpdateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderReq proto.InternalMessageInfo

func (m *UpdateOrderReq) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateOrderRes struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateOrderRes) Reset()         { *m = UpdateOrderRes{} }
func (m *UpdateOrderRes) String() string { return proto.CompactTextString(m) }
func (*UpdateOrderRes) ProtoMessage()    {}
func (*UpdateOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *UpdateOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateOrderRes.Unmarshal(m, b)
}
func (m *UpdateOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateOrderRes.Marshal(b, m, deterministic)
}
func (m *UpdateOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateOrderRes.Merge(m, src)
}
func (m *UpdateOrderRes) XXX_Size() int {
	return xxx_messageInfo_UpdateOrderRes.Size(m)
}
func (m *UpdateOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateOrderRes proto.InternalMessageInfo

func (m *UpdateOrderRes) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

type DeleteOrderReq struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderReq) Reset()         { *m = DeleteOrderReq{} }
func (m *DeleteOrderReq) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderReq) ProtoMessage()    {}
func (*DeleteOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *DeleteOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderReq.Unmarshal(m, b)
}
func (m *DeleteOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderReq.Marshal(b, m, deterministic)
}
func (m *DeleteOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderReq.Merge(m, src)
}
func (m *DeleteOrderReq) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderReq.Size(m)
}
func (m *DeleteOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderReq proto.InternalMessageInfo

func (m *DeleteOrderReq) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteOrderRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteOrderRes) Reset()         { *m = DeleteOrderRes{} }
func (m *DeleteOrderRes) String() string { return proto.CompactTextString(m) }
func (*DeleteOrderRes) ProtoMessage()    {}
func (*DeleteOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *DeleteOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteOrderRes.Unmarshal(m, b)
}
func (m *DeleteOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteOrderRes.Marshal(b, m, deterministic)
}
func (m *DeleteOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteOrderRes.Merge(m, src)
}
func (m *DeleteOrderRes) XXX_Size() int {
	return xxx_messageInfo_DeleteOrderRes.Size(m)
}
func (m *DeleteOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteOrderRes proto.InternalMessageInfo

func (m *DeleteOrderRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ListOrderReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderReq) Reset()         { *m = ListOrderReq{} }
func (m *ListOrderReq) String() string { return proto.CompactTextString(m) }
func (*ListOrderReq) ProtoMessage()    {}
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *ListOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderReq.Unmarshal(m, b)
}
func (m *ListOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderReq.Marshal(b, m, deterministic)
}
func (m *ListOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderReq.Merge(m, src)
}
func (m *ListOrderReq) XXX_Size() int {
	return xxx_messageInfo_ListOrderReq.Size(m)
}
func (m *ListOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderReq proto.InternalMessageInfo

type ListOrderRes struct {
	Item                 *Order   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOrderRes) Reset()         { *m = ListOrderRes{} }
func (m *ListOrderRes) String() string { return proto.CompactTextString(m) }
func (*ListOrderRes) ProtoMessage()    {}
func (*ListOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *ListOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOrderRes.Unmarshal(m, b)
}
func (m *ListOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOrderRes.Marshal(b, m, deterministic)
}
func (m *ListOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOrderRes.Merge(m, src)
}
func (m *ListOrderRes) XXX_Size() int {
	return xxx_messageInfo_ListOrderRes.Size(m)
}
func (m *ListOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListOrderRes proto.InternalMessageInfo

func (m *ListOrderRes) GetItem() *Order {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*Order)(nil), "proto.Order")
	proto.RegisterType((*CreateOrderReq)(nil), "proto.CreateOrderReq")
	proto.RegisterType((*CreateOrderRes)(nil), "proto.CreateOrderRes")
	proto.RegisterType((*ReadOrderReq)(nil), "proto.ReadOrderReq")
	proto.RegisterType((*ReadOrderRes)(nil), "proto.ReadOrderRes")
	proto.RegisterType((*UpdateOrderReq)(nil), "proto.UpdateOrderReq")
	proto.RegisterType((*UpdateOrderRes)(nil), "proto.UpdateOrderRes")
	proto.RegisterType((*DeleteOrderReq)(nil), "proto.DeleteOrderReq")
	proto.RegisterType((*DeleteOrderRes)(nil), "proto.DeleteOrderRes")
	proto.RegisterType((*ListOrderReq)(nil), "proto.ListOrderReq")
	proto.RegisterType((*ListOrderRes)(nil), "proto.ListOrderRes")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x41, 0x8b, 0x9b, 0x40,
	0x18, 0x45, 0x13, 0x63, 0xf2, 0x29, 0x1e, 0xa6, 0x94, 0x4e, 0x3d, 0xb4, 0xd6, 0x93, 0xf4, 0x10,
	0x82, 0xa5, 0x50, 0xe8, 0xb1, 0xbd, 0x04, 0x4a, 0x1b, 0xa6, 0xec, 0x59, 0x4c, 0x66, 0x0e, 0x03,
	0xc9, 0xea, 0xce, 0x37, 0x59, 0xc8, 0x1f, 0xdb, 0x7f, 0xb0, 0xff, 0x6b, 0x99, 0xd1, 0x88, 0x66,
	0x3d, 0xb8, 0x27, 0x79, 0xef, 0xfb, 0x9e, 0xef, 0xcd, 0xfb, 0x20, 0xa8, 0x14, 0x17, 0x6a, 0x5d,
	0xab, 0x4a, 0x57, 0xc4, 0xb3, 0x9f, 0x18, 0xa4, 0x16, 0xa7, 0x86, 0x4a, 0x9f, 0x1d, 0xf0, 0xfe,
	0x99, 0x15, 0x12, 0x81, 0x2b, 0x39, 0x75, 0x12, 0x27, 0x5b, 0x31, 0x57, 0x72, 0xf2, 0x11, 0x96,
	0xba, 0xdc, 0x1f, 0x45, 0x71, 0x5f, 0x51, 0x37, 0x71, 0x32, 0x8f, 0xf9, 0x16, 0xff, 0xad, 0xc8,
	0x07, 0xf0, 0xcf, 0x28, 0x54, 0x21, 0x39, 0x9d, 0xd9, 0xfd, 0x85, 0x81, 0x5b, 0x4e, 0xbe, 0x80,
	0x67, 0xfe, 0x8d, 0x74, 0x9e, 0xcc, 0xb2, 0x20, 0x0f, 0x1a, 0x93, 0xf5, 0x56, 0x8b, 0x13, 0x6b,
	0x26, 0xe4, 0x33, 0x04, 0xba, 0xd2, 0xe5, 0xb1, 0xa8, 0x95, 0x3c, 0x08, 0xea, 0x25, 0x4e, 0xe6,
	0x32, 0xb0, 0xd4, 0xce, 0x30, 0xc6, 0x57, 0x62, 0x51, 0x97, 0x17, 0xc1, 0xe9, 0x22, 0x71, 0xb2,
	0x25, 0xf3, 0x25, 0xee, 0x0c, 0x6c, 0x47, 0x4a, 0x94, 0xfc, 0x42, 0xfd, 0xeb, 0x88, 0x19, 0x98,
	0xe6, 0x10, 0xfd, 0x52, 0xa2, 0xd4, 0xc2, 0x3e, 0x86, 0x89, 0x07, 0x92, 0xc0, 0xdc, 0x38, 0xda,
	0x17, 0x05, 0x79, 0xd8, 0x46, 0x69, 0xc6, 0x76, 0xf2, 0x4a, 0x83, 0x13, 0x34, 0x9f, 0x20, 0x34,
	0x86, 0x9d, 0xcb, 0x4d, 0x6b, 0xe9, 0x66, 0x30, 0xc7, 0x69, 0x29, 0xee, 0x6a, 0xfe, 0xe6, 0xe4,
	0x03, 0xcd, 0x14, 0x9f, 0x04, 0xa2, 0xdf, 0xe2, 0x28, 0x7a, 0x3e, 0xb7, 0xd9, 0xbf, 0xde, 0x6c,
	0x20, 0xa1, 0xe0, 0xe3, 0xf9, 0x70, 0x10, 0x88, 0x76, 0x6d, 0xc9, 0xae, 0x30, 0x8d, 0x20, 0xfc,
	0x23, 0x51, 0x5f, 0xff, 0x65, 0xde, 0xdd, 0xc3, 0x13, 0xf2, 0xe4, 0x4f, 0x2e, 0x84, 0x16, 0xff,
	0x17, 0xea, 0xd1, 0x1c, 0xfe, 0x27, 0x04, 0xbd, 0x73, 0x90, 0xf7, 0xad, 0x66, 0x78, 0xd6, 0x78,
	0x94, 0x46, 0xf2, 0x1d, 0x56, 0x5d, 0xef, 0xe4, 0x5d, 0xbb, 0xd3, 0xbf, 0x54, 0x3c, 0x42, 0xa2,
	0xf1, 0xec, 0x15, 0xd9, 0x79, 0x0e, 0x0f, 0x12, 0x8f, 0xd2, 0x56, 0xdc, 0xeb, 0xab, 0x13, 0x0f,
	0x5b, 0x8e, 0x47, 0x69, 0x24, 0x3f, 0x00, 0xba, 0xc2, 0xb0, 0x4b, 0xdc, 0xef, 0x34, 0x1e, 0x21,
	0x71, 0xe3, 0xec, 0x17, 0x96, 0xfd, 0xf6, 0x12, 0x00, 0x00, 0xff, 0xff, 0x4e, 0x24, 0x6d, 0xa5,
	0xdb, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error)
	ReadOrder(ctx context.Context, in *ReadOrderReq, opts ...grpc.CallOption) (*ReadOrderRes, error)
	UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderRes, error)
	DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderRes, error)
	ListOrders(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (OrderService_ListOrdersClient, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error) {
	out := new(CreateOrderRes)
	err := c.cc.Invoke(ctx, "/proto.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ReadOrder(ctx context.Context, in *ReadOrderReq, opts ...grpc.CallOption) (*ReadOrderRes, error) {
	out := new(ReadOrderRes)
	err := c.cc.Invoke(ctx, "/proto.OrderService/ReadOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrder(ctx context.Context, in *UpdateOrderReq, opts ...grpc.CallOption) (*UpdateOrderRes, error) {
	out := new(UpdateOrderRes)
	err := c.cc.Invoke(ctx, "/proto.OrderService/UpdateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DeleteOrder(ctx context.Context, in *DeleteOrderReq, opts ...grpc.CallOption) (*DeleteOrderRes, error) {
	out := new(DeleteOrderRes)
	err := c.cc.Invoke(ctx, "/proto.OrderService/DeleteOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrderReq, opts ...grpc.CallOption) (OrderService_ListOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/proto.OrderService/ListOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceListOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderService_ListOrdersClient interface {
	Recv() (*ListOrderRes, error)
	grpc.ClientStream
}

type orderServiceListOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceListOrdersClient) Recv() (*ListOrderRes, error) {
	m := new(ListOrderRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRes, error)
	ReadOrder(context.Context, *ReadOrderReq) (*ReadOrderRes, error)
	UpdateOrder(context.Context, *UpdateOrderReq) (*UpdateOrderRes, error)
	DeleteOrder(context.Context, *DeleteOrderReq) (*DeleteOrderRes, error)
	ListOrders(*ListOrderReq, OrderService_ListOrdersServer) error
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderReq) (*CreateOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) ReadOrder(ctx context.Context, req *ReadOrderReq) (*ReadOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadOrder not implemented")
}
func (*UnimplementedOrderServiceServer) UpdateOrder(ctx context.Context, req *UpdateOrderReq) (*UpdateOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrder not implemented")
}
func (*UnimplementedOrderServiceServer) DeleteOrder(ctx context.Context, req *DeleteOrderReq) (*DeleteOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOrder not implemented")
}
func (*UnimplementedOrderServiceServer) ListOrders(req *ListOrderReq, srv OrderService_ListOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method ListOrders not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ReadOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ReadOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/ReadOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ReadOrder(ctx, req.(*ReadOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/UpdateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrder(ctx, req.(*UpdateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DeleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DeleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.OrderService/DeleteOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DeleteOrder(ctx, req.(*DeleteOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOrderReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).ListOrders(m, &orderServiceListOrdersServer{stream})
}

type OrderService_ListOrdersServer interface {
	Send(*ListOrderRes) error
	grpc.ServerStream
}

type orderServiceListOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceListOrdersServer) Send(m *ListOrderRes) error {
	return x.ServerStream.SendMsg(m)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "ReadOrder",
			Handler:    _OrderService_ReadOrder_Handler,
		},
		{
			MethodName: "UpdateOrder",
			Handler:    _OrderService_UpdateOrder_Handler,
		},
		{
			MethodName: "DeleteOrder",
			Handler:    _OrderService_DeleteOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListOrders",
			Handler:       _OrderService_ListOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order.proto",
}
